### ISSUE TITLE
Checklist on whats left to get this functioning

### ISSUE THREAD

**Issue by theresa-m** [theresa-m/clo-lift-test#1]
- [x] run method should fill in custom URL for project
- [x] IN PROGERSS Confirm that PR runs show # of test fixed
- [x] disable lift tools + test
- [x] working installTool method
- [ ] enable for all CLOMonitor checks, not just security
- [ ] README and project installation instructions
- [x] rename repo to something more meaningful
- [ ] open a PR for clomonitor/scorecard around adding more details entries?
- [ ] Test locally - run and take that output, display on lift console
- [ ] Test w/github auth

**Comment by theresa-m** [comment]
I no longer plan to work on this.
